import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { CheckCircle2, Clock3, Headset, MessageCircle, Send } from "lucide-react";
import { api, CHAT_WS_URL, ChatConversation, ChatMessage, Me } from "../api";

export function SupportChatEmbed({ me, sourceApp }: { me: Me; sourceApp: string }) {
  const [chat, setChat] = useState<ChatConversation | null>(null);
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const threadRef = useRef<HTMLDivElement>(null);
  const reload = useCallback(async () => { const current = await api.currentSupportChat(sourceApp); setChat(current); if (current) { setMessages(await api.chatMessages(current.id)); await api.markChatRead(current.id); } }, [sourceApp]);
  useEffect(() => { reload().catch((err) => setError(err.message)); }, [reload]);
  useEffect(() => { let ws: WebSocket | null = null; let timer = 0; let stop = false; const connect = () => { ws = new WebSocket(CHAT_WS_URL); ws.onmessage = () => reload().catch(() => {}); ws.onclose = () => { if (!stop) timer = window.setTimeout(connect, 1800); }; }; connect(); return () => { stop = true; clearTimeout(timer); ws?.close(); }; }, [reload]);
  useEffect(() => { threadRef.current?.scrollTo({ top: threadRef.current.scrollHeight, behavior: "smooth" }); }, [messages]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!message.trim()) return; setBusy(true); setError(""); try { if (!chat) await api.createSupportChat(sourceApp, message.trim()); else await api.sendChatMessage(chat.id, message.trim()); setMessage(""); await reload(); } catch (err: any) { setError(err.message ?? "No se pudo enviar el mensaje."); } finally { setBusy(false); } }
  if (!chat) return <main className="support-embed-welcome"><span><Headset size={28}/></span><h2>¿Necesitas ayuda?</h2><p>Inicia un chat y un administrador disponible podrá atenderte.</p><form onSubmit={submit}><textarea value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Cuéntanos brevemente en qué necesitas ayuda" maxLength={4000}/><button disabled={busy || !message.trim()}><MessageCircle size={17}/> Iniciar chat</button></form>{error && <small className="support-embed-error">{error}</small>}</main>;
  return <main className="support-embed-chat"><header><div><Headset size={20}/><span><strong>Ayuda con un administrador</strong><small>{chat.status === "open" ? "Esperando a un administrador" : `Atendido por ${chat.claimed_by?.full_name ?? "un administrador"}`}</small></span></div><b className={`support-status ${chat.status}`}>{chat.status === "open" ? <Clock3 size={14}/> : <CheckCircle2 size={14}/>} {chat.status === "open" ? "En espera" : "En atención"}</b></header><div className="chat-thread" ref={threadRef}>{messages.map((item) => <div className={`chat-message-row ${item.sender_user_id === me.id ? "mine" : "theirs"}`} key={item.id}><div className="chat-message-bubble"><strong>{item.sender_name}</strong><p>{item.body}</p><time>{new Date(item.created_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</time></div></div>)}</div><form className="chat-composer" onSubmit={submit}><input value={message} onChange={(e) => setMessage(e.target.value)} placeholder={chat.status === "open" ? "Puedes agregar más información..." : "Escribe tu mensaje..."} maxLength={4000}/><button disabled={busy || !message.trim()}><Send size={18}/></button></form>{error && <small className="support-embed-error">{error}</small>}</main>;
}
